// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8lvh-mFAw9NEIe5m1Kx-IKz6kjwS5FiY',
    appId: '1:712220627429:web:85fdf5563ccbb4b39c5f0c',
    messagingSenderId: '712220627429',
    projectId: 'meracatalog-acb30',
    authDomain: 'meracatalog-acb30.firebaseapp.com',
    storageBucket: 'meracatalog-acb30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwb9pyTTU6jxkV7zPRVym3Bbb20XZUk-c',
    appId: '1:712220627429:android:26e16639fa6fa1829c5f0c',
    messagingSenderId: '712220627429',
    projectId: 'meracatalog-acb30',
    storageBucket: 'meracatalog-acb30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMCHuOC0GsXJA5oORXhHr3nUyR1_Zwtow',
    appId: '1:712220627429:ios:3ef6ca1aed7eb2ca9c5f0c',
    messagingSenderId: '712220627429',
    projectId: 'meracatalog-acb30',
    storageBucket: 'meracatalog-acb30.firebasestorage.app',
    iosBundleId: 'com.example.meracatalog',
  );
}
