// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQfLTpjzypJ3cCvxt98LCVd_LGyXhGIs',
    appId: '1:229965864511:web:6cfdf2dd0091583b6b228a',
    messagingSenderId: '229965864511',
    projectId: 'supplier-catalogue',
    authDomain: 'supplier-catalogue.firebaseapp.com',
    storageBucket: 'supplier-catalogue.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7UDhozSAi2ttgiGdNtbGsf1Nz-91_e6Y',
    appId: '1:229965864511:android:00d922a3cbe3b7756b228a',
    messagingSenderId: '229965864511',
    projectId: 'supplier-catalogue',
    storageBucket: 'supplier-catalogue.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjl4XKveQqWpNjCxar61X5Q_jdi2ykdgA',
    appId: '1:229965864511:ios:aaa9d06745374fde6b228a',
    messagingSenderId: '229965864511',
    projectId: 'supplier-catalogue',
    storageBucket: 'supplier-catalogue.firebasestorage.app',
    iosBundleId: 'com.example.supplierCatalogue',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjl4XKveQqWpNjCxar61X5Q_jdi2ykdgA',
    appId: '1:229965864511:ios:aaa9d06745374fde6b228a',
    messagingSenderId: '229965864511',
    projectId: 'supplier-catalogue',
    storageBucket: 'supplier-catalogue.firebasestorage.app',
    iosBundleId: 'com.example.supplierCatalogue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQfLTpjzypJ3cCvxt98LCVd_LGyXhGIs',
    appId: '1:229965864511:web:fffe3e9cc70185176b228a',
    messagingSenderId: '229965864511',
    projectId: 'supplier-catalogue',
    authDomain: 'supplier-catalogue.firebaseapp.com',
    storageBucket: 'supplier-catalogue.firebasestorage.app',
  );
}
